Improve the XML extracting

diff --git a/lldp/aci-lldp/files/opt/bin/lldp-export b/lldp/aci-lldp/files/opt/bin/lldp-export
--- a/lldp/aci-lldp/files/opt/bin/lldp-export
+++ b/lldp/aci-lldp/files/opt/bin/lldp-export
@@ -1,11 +1,38 @@
 #!/bin/bash
 
-OUTPUT=/var/run/lldp.xml
 
-for i in {0..90}
+echo "Start $0"
+
+set -o pipefail
+
+
+SOCKET=/var/run/lldpd.socket
+
+for i in {0..60}
 do
-    lldpctl -f xml | tee ${OUTPUT}
-    test $(cat ${OUTPUT} | wc -l) -gt 3 && break
-    echo "Fail to run $0 attempt ${i}" >&2
+    test -S ${SOCKET} && break
+    echo "$0 without any socket: ${SOCKET} attempt ${i}/60"
     sleep 1
 done
+
+test ! -S ${SOCKET} && echo "$0 without any socket: ${SOCKET} exit 1" && exit 1
+ls -l ${SOCKET}
+
+echo "Warm UP..."
+lldpctl -f keyvalue
+echo "Warm DONE"
+
+OUTPUT=/var/run/lldp.xml
+
+for j in {0..120}
+do
+    # ${SOCKET} have to be /var/run/lldpd.socket
+    lldpctl -f keyvalue
+    lldpctl -f xml > ${OUTPUT}
+    test $(cat ${OUTPUT} | wc -l) -gt 2 && echo "$0 with content in ${OUTPUT}" && exit 0
+    echo "Fail to run $0 attempt ${j}/120"
+    sleep 1
+done
+
+echo "Fail to run $0 exit 2"
+exit 2
