Lifecycle handler, kexec, coreos-install reporting, generic SQL for cockroachdb pg

diff --git a/app/tests/test_matchbox/ignition/euid-discovery-no-lldp.yaml b/app/tests/test_matchbox/ignition/euid-discovery-no-lldp.yaml
--- a/app/tests/test_matchbox/ignition/euid-discovery-no-lldp.yaml
+++ b/app/tests/test_matchbox/ignition/euid-discovery-no-lldp.yaml
@@ -98,16 +98,25 @@ storage:
               TIMER=60
           fi
 
+          QUERY=${REQUEST_RAW_QUERY}{{if index . "extra_selectors"}}&{{.extra_selectors}}{{end}}
+
           while true
           do
-              curl -f ${API_URI}/ignition?${REQUEST_RAW_QUERY} -o ${NEW_IGNITION}
-
-              diff /run/ignition.json ${NEW_IGNITION}
               curl -f ${API_URI}/scheduler | jq -e ". | has(${NORMALIZED_MAC})"
               if [ $? -eq 0 ]
               then
+                  sleep 1
+                  curl -o ${NEW_IGNITION} -f \
+                    ${API_URI}/ignition?${QUERY} || continue
+                  ls -l /run/ignition.json ${NEW_IGNITION}
                   udevadm settle
-                  systemctl poweroff
+                  #coreos-install -d /dev/sda -V current -C stable -i ${NEW_IGNITION} || {
+                  #  curl -f -XPOST \
+                  #    "${API_URI}/lifecycle/coreos-install/${QUERY}/fail"
+                  #  exit 2
+                  #}
+                  curl -f -XPOST "${API_URI}/lifecycle/coreos-install/${QUERY}/success"
+                  systemctl reboot
               fi
               sleep ${TIMER}
           done
