Service account token support, refactoring pki

diff --git a/matchbox/ignition/etcd-member-kubernetes-control-plane.yaml b/matchbox/ignition/etcd-member-kubernetes-control-plane.yaml
--- a/matchbox/ignition/etcd-member-kubernetes-control-plane.yaml
+++ b/matchbox/ignition/etcd-member-kubernetes-control-plane.yaml
@@ -317,23 +317,45 @@ systemd:
         [Install]
         WantedBy=multi-user.target
 
-    - name: vault-certs-peer@etcd-kubernetes.service
+    - name: vault-token-kube-apiserver@kubernetes.service
       enable: true
       contents: |
         [Service]
-        EnvironmentFile=/etc/vault.d/etcd-kubernetes/peer.token
-        ExecStart=/opt/bin/vault-certs %i peer
+        ExecStartPre=/bin/mkdir -pv /etc/vault.d/%i
+        ExecStart=/opt/bin/vault-token %i kube-apiserver
         RestartSec=60
         Restart=always
         [Install]
         WantedBy=multi-user.target
 
-    - name: vault-certs-client@etcd-kubernetes.service
+    - name: vault-pki-peer@etcd-kubernetes.service
+      enable: true
+      contents: |
+        [Service]
+        EnvironmentFile=/etc/vault.d/etcd-kubernetes/peer.token
+        ExecStart=/opt/bin/vault-pki %i peer
+        RestartSec=60
+        Restart=always
+        [Install]
+        WantedBy=multi-user.target
+
+    - name: vault-pki-client@etcd-kubernetes.service
       enable: true
       contents: |
         [Service]
         EnvironmentFile=/etc/vault.d/etcd-kubernetes/client.token
-        ExecStart=/opt/bin/vault-certs %i client
+        ExecStart=/opt/bin/vault-pki %i client
+        RestartSec=60
+        Restart=always
+        [Install]
+        WantedBy=multi-user.target
+
+    - name: vault-secret-service-accounts@kubernetes.service
+      enable: true
+      contents: |
+        [Service]
+        EnvironmentFile=/etc/vault.d/kubernetes/kube-apiserver.token
+        ExecStart=/opt/bin/vault-secret %i service-accounts
         RestartSec=60
         Restart=always
         [Install]
@@ -543,15 +565,19 @@ storage:
               command:
               - /hyperkube
               - apiserver
-              - --bind-address=0.0.0.0
-              - --insecure-bind-address=0.0.0.0
-              - --etcd-servers={{.kubernetes_etcd_servers}}
+              - --bind-address={{.network.ip}}
+              - --insecure-bind-address=127.0.0.1
+              - --etcd-servers=http://127.0.0.1:{{.kubernetes_etcd_client_port}}
               - --allow-privileged=true
               - --service-cluster-ip-range={{.kubernetes_service_cluster_ip_range}}
               - --admission-control=NamespaceLifecycle,LimitRanger,DefaultStorageClass,ResourceQuota
               - --runtime-config=batch/v2alpha1
               - --apiserver-count={{.kubernetes_apiserver_count}}
               - --enable-swagger-ui=true
+              - --tls-ca-file=/etc/secrets/kube-apiserver.issuing_ca
+              - --tls-cert-file=/etc/secrets/kube-apiserver.certificate
+              - --tls-private-key-file=/etc/secrets/kube-apiserver.private_key
+              - --service-account-key-file=/etc/secrets/service-accounts.key
               resources:
                 requests:
                   cpu: 200m
@@ -563,13 +589,13 @@ storage:
                 initialDelaySeconds: 15
                 timeoutSeconds: 15
               volumeMounts:
-              - name: kubernetes
-                mountPath: /var/lib/kubernetes
+              - name: secrets
+                mountPath: /etc/secrets
                 readOnly: true
             volumes:
-            - name: kubernetes
+            - name: secrets
               hostPath:
-                path: /var/lib/kubernetes
+                path: /etc/vault.d/kubernetes
 
     - path: /etc/kubernetes/manifests/kube-controller-manager.yaml
       filesystem: root
@@ -1000,9 +1026,9 @@ storage:
           echo "Update enable by strategy: ${STRATEGY}"
 
           echo "locksmithctl operations..."
-          locksmithctl -endpoint {{.kubernetes_etcd_servers}} status
-          locksmithctl -endpoint {{.kubernetes_etcd_servers}} unlock "${REQUEST_RAW_QUERY}" || true
-          locksmithctl -endpoint {{.kubernetes_etcd_servers}} lock "${REQUEST_RAW_QUERY}"
+          locksmithctl -endpoint http://127.0.0.1:{{.fleet_etcd_client_port}} status
+          locksmithctl -endpoint http://127.0.0.1:{{.fleet_etcd_client_port}} unlock "${REQUEST_RAW_QUERY}" || true
+          locksmithctl -endpoint http://127.0.0.1:{{.fleet_etcd_client_port}} lock "${REQUEST_RAW_QUERY}"
 
           echo "stopping fleet..."
           systemctl stop fleet.service
@@ -1125,8 +1151,6 @@ storage:
 
           vault mount -path pki/etcd-kubernetes pki
           vault mount-tune -max-lease-ttl=87600h pki/etcd-kubernetes
-          vault mounts
-
           vault write pki/etcd-kubernetes/root/generate/internal common_name=etcd-kubernetes ttl=87600h # 10y
           vault write pki/etcd-kubernetes/roles/peer allow_any_name=true max_ttl=720h # 30j
           vault write pki/etcd-kubernetes/roles/client allow_any_name=true max_ttl=720h # 30j
@@ -1156,6 +1180,45 @@ storage:
             -policy="etcd-kubernetes/client" | jq -er .auth.client_token | \
               etcdctl --no-sync --endpoints http://127.0.0.1:{{.vault_etcd_client_port}} \
                 set token/etcd-kubernetes/client
+
+          openssl genrsa 4096 | vault write "secret/kubernetes/service-accounts" key=-
+
+          vault mount -path pki/kubernetes pki
+          vault mount-tune -max-lease-ttl=87600h pki/kubernetes
+          vault write pki/kubernetes/root/generate/internal common_name=kubernetes ttl=87600h # 10y
+          vault write pki/kubernetes/roles/kube-apiserver allow_any_name=true max_ttl=720h # 30j
+          vault write pki/kubernetes/roles/kubelet allow_any_name=true max_ttl=720h # 30j
+
+          vault policy-write kubernetes/kube-apiserver - << EOF
+          path "pki/kubernetes/issue/kube-apiserver" {
+            policy = "write"
+          }
+          path "secret/kubernetes/service-accounts" {
+            policy = "read"
+          }
+          EOF
+
+          vault policy-write kubernetes/kubelet - << EOF
+          path "pki/kubernetes/issue/kubelet" {
+            policy = "write"
+          }
+          EOF
+
+          vault token-create -format=json \
+            -display-name kubernetes/kube-apiserver \
+            -ttl="8760h" -orphan -period="8760h" \
+            -policy="kubernetes/kube-apiserver" | jq -er .auth.client_token | \
+              etcdctl --no-sync --endpoints http://127.0.0.1:{{.vault_etcd_client_port}} \
+                set token/kubernetes/kube-apiserver
+
+          vault token-create -format=json \
+            -display-name kubernetes/kubelet \
+            -ttl="8760h" -orphan -period="8760h" \
+            -policy="kubernetes/kubelet" | jq -er .auth.client_token | \
+              etcdctl --no-sync --endpoints http://127.0.0.1:{{.vault_etcd_client_port}} \
+                set token/kubernetes/kubelet
+
+
 
     - path: /opt/bin/vault-token
       mode: 0544
@@ -1202,7 +1265,7 @@ storage:
             sleep 5
           done
 
-    - path: /opt/bin/vault-certs
+    - path: /opt/bin/vault-pki
       mode: 0544
       filesystem: root
       contents:
@@ -1226,7 +1289,7 @@ storage:
           }
 
           # TODO consul-template or check if renew
-          test -f /etc/vault.d/${1}/${2}-certs.json && exit 0
+          test -f /etc/vault.d/${1}/${2}-pki.json && exit 0
 
           while true
           do
@@ -1238,12 +1301,59 @@ storage:
               vault write -format=json pki/${1}/issue/${2} \
                 common_name={{.network.ip}} \
                 ip_sans={{.etcd_member_kubernetes_control_plane_ip_list}} \
-                  > /etc/vault.d/${1}/${2}-certs.json
+                  > /etc/vault.d/${1}/${2}-pki.json
               if [ $? -eq 0 ]
               then
                 for item in certificate issuing_ca private_key
                 do
-                  jq -re .data.${item} /etc/vault.d/${1}/${2}-certs.json > /etc/vault.d/${1}/${2}.${item}
+                  jq -re .data.${item} /etc/vault.d/${1}/${2}-pki.json > /etc/vault.d/${1}/${2}.${item}
+                done
+                exit 0
+              fi
+            done
+            sleep 5
+          done
+
+    - path: /opt/bin/vault-secret
+      mode: 0544
+      filesystem: root
+      contents:
+        inline: |
+          #!/usr/bin/env bash
+
+          export PATH=/opt/bin:${PATH}
+          set -o pipefail
+
+          test ${1} || {
+            echo 'missing $1 eg: kubernetes'
+            exit 2
+          }
+          test ${2} || {
+            echo 'missing $2 eg: service-accounts'
+            exit 2
+          }
+          test ${TOKEN} || {
+            echo 'missing ${TOKEN}'
+            exit 2
+          }
+
+          # TODO consul-template or check if renew
+          test -f /etc/vault.d/${1}/${2}-secret.json && exit 0
+
+          while true
+          do
+            for ve in $(echo -n {{ .vault_ip_list }} | tr ',' ' ')
+            do
+              export VAULT_ADDR="http://${ve}:8200"
+              vault auth ${TOKEN} || continue
+
+              vault read -format=json secret/${1}/${2} \
+                  > /etc/vault.d/${1}/${2}-secret.json
+              if [ $? -eq 0 ]
+              then
+                for item in key
+                do
+                  jq -re .data.${item} /etc/vault.d/${1}/${2}-secret.json > /etc/vault.d/${1}/${2}.${item}
                 done
                 exit 0
               fi
diff --git a/matchbox/ignition/kubernetes-node.yaml b/matchbox/ignition/kubernetes-node.yaml
--- a/matchbox/ignition/kubernetes-node.yaml
+++ b/matchbox/ignition/kubernetes-node.yaml
@@ -226,12 +226,12 @@ systemd:
         [Install]
         WantedBy=multi-user.target
 
-    - name: vault-certs-client@etcd-kubernetes.service
+    - name: vault-pki-client@etcd-kubernetes.service
       enable: true
       contents: |
         [Service]
         EnvironmentFile=/etc/vault.d/etcd-kubernetes/client.token
-        ExecStart=/opt/bin/vault-certs %i client
+        ExecStart=/opt/bin/vault-pki %i client
         RestartSec=60
         Restart=always
         [Install]
@@ -431,9 +431,9 @@ storage:
               - /hyperkube
               - apiserver
               - proxy
-              - --bind-address=0.0.0.0
-              - --insecure-bind-address=0.0.0.0
-              - --etcd-servers={{.kubernetes_etcd_servers}}
+              - --bind-address={{.network.ip}}
+              - --insecure-bind-address=127.0.0.1
+              - --etcd-servers=http://127.0.0.1:{{.kubernetes_etcd_client_port}}
               - --service-cluster-ip-range={{.kubernetes_service_cluster_ip_range}}
               resources:
                 requests:
@@ -445,14 +445,6 @@ storage:
                   path: /healthz
                 initialDelaySeconds: 15
                 timeoutSeconds: 15
-              volumeMounts:
-              - name: kubernetes
-                mountPath: /var/lib/kubernetes
-                readOnly: true
-            volumes:
-            - name: kubernetes
-              hostPath:
-                path: /var/lib/kubernetes
 
     - path: /etc/metadata.env
       filesystem: root
@@ -664,9 +656,9 @@ storage:
           echo "Update enable by strategy: ${STRATEGY}"
 
           echo "locksmithctl operations..."
-          locksmithctl -endpoint {{.kubernetes_etcd_servers}} status
-          locksmithctl -endpoint {{.kubernetes_etcd_servers}} unlock "${REQUEST_RAW_QUERY}" || true
-          locksmithctl -endpoint {{.kubernetes_etcd_servers}} lock "${REQUEST_RAW_QUERY}"
+          locksmithctl -endpoint http://127.0.0.1:{{.fleet_etcd_client_port}} status
+          locksmithctl -endpoint http://127.0.0.1:{{.fleet_etcd_client_port}} unlock "${REQUEST_RAW_QUERY}" || true
+          locksmithctl -endpoint http://127.0.0.1:{{.fleet_etcd_client_port}} lock "${REQUEST_RAW_QUERY}"
 
           echo "stopping fleet..."
           systemctl stop fleet.service
@@ -794,7 +786,7 @@ storage:
             sleep 5
           done
 
-    - path: /opt/bin/vault-certs
+    - path: /opt/bin/vault-pki
       mode: 0544
       filesystem: root
       contents:
@@ -818,7 +810,7 @@ storage:
           }
 
           # TODO consul-template or check if renew
-          test -f /etc/vault.d/${1}/${2}-certs.json && exit 0
+          test -f /etc/vault.d/${1}/${2}-pki.json && exit 0
 
           while true
           do
@@ -830,12 +822,59 @@ storage:
               vault write -format=json pki/${1}/issue/${2} \
                 common_name={{.network.ip}} \
                 ip_sans={{.etcd_member_kubernetes_control_plane_ip_list}} \
-                  > /etc/vault.d/${1}/${2}-certs.json
+                  > /etc/vault.d/${1}/${2}-pki.json
               if [ $? -eq 0 ]
               then
                 for item in certificate issuing_ca private_key
                 do
-                  jq -re .data.${item} /etc/vault.d/${1}/${2}-certs.json > /etc/vault.d/${1}/${2}.${item}
+                  jq -re .data.${item} /etc/vault.d/${1}/${2}-pki.json > /etc/vault.d/${1}/${2}.${item}
+                done
+                exit 0
+              fi
+            done
+            sleep 5
+          done
+
+    - path: /opt/bin/vault-secret
+      mode: 0544
+      filesystem: root
+      contents:
+        inline: |
+          #!/usr/bin/env bash
+
+          export PATH=/opt/bin:${PATH}
+          set -o pipefail
+
+          test ${1} || {
+            echo 'missing $1 eg: kubernetes'
+            exit 2
+          }
+          test ${2} || {
+            echo 'missing $2 eg: service-accounts'
+            exit 2
+          }
+          test ${TOKEN} || {
+            echo 'missing ${TOKEN}'
+            exit 2
+          }
+
+          # TODO consul-template or check if renew
+          test -f /etc/vault.d/${1}/${2}-secret.json && exit 0
+
+          while true
+          do
+            for ve in $(echo -n {{ .vault_ip_list }} | tr ',' ' ')
+            do
+              export VAULT_ADDR="http://${ve}:8200"
+              vault auth ${TOKEN} || continue
+
+              vault read -format=json secret/${1}/${2} \
+                  > /etc/vault.d/${1}/${2}-secret.json
+              if [ $? -eq 0 ]
+              then
+                for item in key
+                do
+                  jq -re .data.${item} /etc/vault.d/${1}/${2}-secret.json > /etc/vault.d/${1}/${2}.${item}
                 done
                 exit 0
               fi
