First step for Vault certs

diff --git a/matchbox/ignition/etcd-member-kubernetes-control-plane.yaml b/matchbox/ignition/etcd-member-kubernetes-control-plane.yaml
--- a/matchbox/ignition/etcd-member-kubernetes-control-plane.yaml
+++ b/matchbox/ignition/etcd-member-kubernetes-control-plane.yaml
@@ -48,28 +48,6 @@ systemd:
         [Install]
         WantedBy=multi-user.target
 
-    - name: install-consul.service
-      enable: true
-      contents: |
-        [Unit]
-        Requires=network-online.target
-        After=network-online.target
-        AssertFileIsExecutable=!/opt/rootfs/usr/bin/consul
-        [Service]
-        Type=oneshot
-        Environment=IMAGE={{.consul_image_url}}
-        ExecStartPre=/usr/bin/rkt fetch --insecure-options=all $IMAGE
-        ExecStartPre=/usr/bin/rkt image export $IMAGE /tmp/%p.aci
-        ExecStartPre=/usr/bin/rkt image rm $IMAGE
-        ExecStartPre=/usr/bin/tar -C /opt/rootfs -xvf /tmp/%p.aci --strip-components=1
-        ExecStartPre=/bin/rm -v /tmp/%p.aci
-
-        ExecStart=/usr/bin/ln -sfv /opt/rootfs/usr/bin/consul /opt/bin/consul
-        ExecReload=-/bin/rm -v /opt/rootfs/usr/bin/consul
-        RemainAfterExit=yes
-        [Install]
-        WantedBy=multi-user.target
-
     - name: install-vault.service
       enable: true
       contents: |
@@ -188,8 +166,6 @@ systemd:
         After=install-fleet.service
         Requires=install-etcd.service
         After=install-etcd.service
-        Requires=install-consul.service
-        After=install-consul.service
         Requires=install-vault.service
         After=install-vault.service
         Requires=install-rkt.service
@@ -234,6 +210,22 @@ systemd:
         [Install]
         RequiredBy=multi-user.target
 
+    - name: etcd-operator@vault.service
+      enable: true
+      contents: |
+        [Unit]
+        After=install-etcd.service
+
+        [Service]
+        EnvironmentFile=/etc/etcd-%i
+        Environment=ETCD_ENV_FILE=/etc/etcd-%i.env
+        ExecStart=/opt/bin/etcd-operator
+        RestartSec=15s
+        Restart=on-failure
+
+        [Install]
+        RequiredBy=multi-user.target
+
     - name: etcd-operator@fleet.service
       enable: true
       contents: |
@@ -257,6 +249,25 @@ systemd:
     - name: etcd2.service
       mask: true
       enable: false
+
+    - name: etcd3@vault.service
+      enable: true
+      contents: |
+        [Unit]
+        After=install-etcd.service
+        Conflicts=etcd.service etcd2.service
+
+        After=etcd-operator@%i.service
+
+        [Service]
+        Type=notify
+        EnvironmentFile=/etc/etcd-%i.env
+        ExecStart=/opt/rootfs/usr/bin/etcd --auto-tls --peer-auto-tls
+        RestartSec=15s
+        Restart=on-failure
+        LimitNOFILE=65826
+        [Install]
+        WantedBy=multi-user.target
 
     - name: etcd3@kubernetes.service
       enable: true
@@ -389,42 +400,12 @@ systemd:
         [Install]
         WantedBy=multi-user.target
 
-    - name: consul.service
-      enable: true
-      contents: |
-        [Unit]
-        After=install-consul.service
-        [Service]
-        ExecStartPre=/bin/mkdir -pv /var/lib/consul
-        ExecStart=/opt/rootfs/usr/bin/consul agent \
-          -advertise={{.network.ip}} \
-          -bootstrap-expect={{.consul_bootstrap_count}} \
-          -data-dir=/var/lib/consul \
-          -server
-        Restart=always
-        RestartSec=10
-        [Install]
-        WantedBy=multi-user.target
-
-    - name: consul-join.service
-      enable: true
-      contents: |
-        [Unit]
-        After=consul.service
-        [Service]
-        ExecStart=/opt/rootfs/usr/bin/consul join \
-          {{ range $element := .consul_server_ip_list }}{{$element}} {{end}}
-        Restart=on-failure
-        RestartSec=10
-        [Install]
-        WantedBy=multi-user.target
-
     - name: vault.service
       enable: true
       contents: |
         [Unit]
         After=install-vault.service
-        After=consul-join.service
+        After=etcd3@vault.service
         [Service]
         ExecStart=/opt/rootfs/usr/bin/vault server -config=/etc/vault.d/
         Restart=always
@@ -453,6 +434,28 @@ systemd:
         [Service]
         ExecStartPre=/opt/bin/vault version
         ExecStart=/opt/bin/vault-unseal
+        RestartSec=2
+        Restart=always
+        [Install]
+        WantedBy=multi-user.target
+
+    - name: vault-token@etcd-kubernetes.service
+      enable: true
+      contents: |
+        [Service]
+        ExecStartPre=/bin/mkdir -pv /etc/vault.d/%i
+        ExecStart=/opt/bin/vault-token %i member
+        RestartSec=2
+        Restart=always
+        [Install]
+        WantedBy=multi-user.target
+
+    - name: vault-certs@etcd-kubernetes.service
+      enable: true
+      contents: |
+        [Service]
+        EnvironmentFile=/etc/vault.d/etcd-kubernetes/member.token
+        ExecStart=/opt/bin/vault-certs %i member
         RestartSec=2
         Restart=always
         [Install]
@@ -617,8 +620,6 @@ storage:
           API_URI='{{.api_uri}}'
           CNI='{{.cni}}'
           CNI_IMAGE_URL='{{.cni_image_url}}'
-          CONSUL_BOOTSTRAP_COUNT={{.consul_bootstrap_count}}
-          CONSUL_IMAGE_URL={{.consul_image_url}}
           DNS_ATTR_DC='{{.dns_attr.dc}}'
           DNS_ATTR_DOMAIN='{{.dns_attr.domain}}'
           DNS_ATTR_POS='{{.dns_attr.pos}}'
@@ -663,6 +664,24 @@ storage:
           RKT_IMAGE_URL='{{.rkt_image_url}}'
           ROLES='{{.roles}}'
           SELECTOR_MAC='{{.selector.mac}}'
+          VAULT_ETCD_ADVERTISE_CLIENT_URLS='{{.fleet_etcd_advertise_client_urls}}'
+          VAULT_ETCD_CLIENT_PORT='{{.fleet_etcd_client_port}}'
+          VAULT_ETCD_DATA_DIR='{{.fleet_etcd_data_dir}}'
+          VAULT_ETCD_INITIAL_ADVERTISE_PEER_URLS='{{.fleet_etcd_initial_advertise_peer_urls}}'
+          VAULT_ETCD_INITIAL_CLUSTER='{{.fleet_etcd_initial_cluster}}'
+          VAULT_ETCD_MEMBER_CLIENT_URI_LIST='{{.fleet_etcd_member_client_uri_list}}'
+          VAULT_ETCD_MEMBER_PEER_URI_LIST='{{.fleet_etcd_member_peer_uri_list}}'
+          VAULT_ETCD_PEER_PORT='{{.fleet_etcd_peer_port}}'
+          VAULT_ETCD_SERVERS='{{.fleet_etcd_servers}}'
+          VAULT_ETCD_ADVERTISE_CLIENT_URLS='{{.vault_etcd_advertise_client_urls}}'
+          VAULT_ETCD_CLIENT_PORT='{{.vault_etcd_client_port}}'
+          VAULT_ETCD_DATA_DIR='{{.vault_etcd_data_dir}}'
+          VAULT_ETCD_INITIAL_ADVERTISE_PEER_URLS='{{.vault_etcd_initial_advertise_peer_urls}}'
+          VAULT_ETCD_INITIAL_CLUSTER='{{.vault_etcd_initial_cluster}}'
+          VAULT_ETCD_MEMBER_CLIENT_URI_LIST='{{.vault_etcd_member_client_uri_list}}'
+          VAULT_ETCD_MEMBER_PEER_URI_LIST='{{.vault_etcd_member_peer_uri_list}}'
+          VAULT_ETCD_PEER_PORT='{{.vault_etcd_peer_port}}'
+          VAULT_ETCD_SERVERS='{{.vault_etcd_servers}}'
           VAULT_IMAGE_URL='{{.vault_image_url}}'
 
     - path: /etc/hostname
@@ -713,9 +732,11 @@ storage:
       mode: 0644
       contents:
         inline: |
-          storage "consul" {
-            address = "127.0.0.1:8500"
-            path    = "vault"
+          storage "etcd" {
+            address  = "http://127.0.0.1:{{.vault_etcd_client_port}}"
+            etcd_api = "v2"
+            ha_enabled = "true"
+            redirect_addr = "http://{{.network.ip}}:8200"
           }
           listener "tcp" {
             address     = "{{.network.ip}}:8200"
@@ -789,6 +810,23 @@ storage:
           ETCD_DATA_DIR={{.fleet_etcd_data_dir}}
           ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:{{.fleet_etcd_client_port}}"
           ETCD_LISTEN_PEER_URLS="http://0.0.0.0:{{.fleet_etcd_peer_port}}"
+
+          NETWORK_IP={{.network.ip}}
+
+    - path: /etc/etcd-vault
+      mode: 0644
+      filesystem: root
+      contents:
+        inline: |
+          ETCD_NAME={{.etcd_name}}
+          ETCD_INITIAL_CLUSTER={{.vault_etcd_initial_cluster}}
+          ETCD_ADVERTISE_CLIENT_URLS="http://127.0.0.1:{{.vault_etcd_client_port}},{{.vault_etcd_advertise_client_urls}}"
+          ETCD_INITIAL_ADVERTISE_PEER_URLS={{.vault_etcd_initial_advertise_peer_urls}}
+          ETCD_MEMBER_CLIENT_URI_LIST={{.vault_etcd_member_client_uri_list}}
+          ETCD_MEMBER_PEER_URI_LIST={{.vault_etcd_member_peer_uri_list}}
+          ETCD_DATA_DIR={{.vault_etcd_data_dir}}
+          ETCD_LISTEN_CLIENT_URLS="http://127.0.0.1:{{.vault_etcd_client_port}},https://{{.network.ip}}:{{.vault_etcd_client_port}}"
+          ETCD_LISTEN_PEER_URLS="https://0.0.0.0:{{.vault_etcd_peer_port}}"
 
           NETWORK_IP={{.network.ip}}
 
@@ -975,67 +1013,52 @@ storage:
 
           test "${REQUEST_RAW_QUERY}" || exit 2
           test "${NETWORK_IP}" || exit 2
+          export PATH=/opt/bin/:${PATH}
 
-          for i in {0..60}
+          until etcdctl -no-sync --endpoints {{.vault_etcd_servers}} cluster-health
           do
-              etcdctl --endpoint {{.kubernetes_etcd_servers}} cluster-health && break
-              sleep 2
+              echo "waiting etcd {{.vault_etcd_servers}}"
+              sleep 1
           done
 
-          for i in {0..60}
+          until etcdctl --endpoint {{.kubernetes_etcd_servers}} cluster-health
           do
-              etcdctl --endpoint {{.fleet_etcd_servers}} cluster-health && break
-              sleep 2
+              echo "waiting etcd {{.kubernetes_etcd_servers}}"
+              sleep 1
           done
 
-          for i in {0..60}
+          until etcdctl --endpoint {{.fleet_etcd_servers}} cluster-health
           do
-              echo "127.0.0.1:{{.kubernetes_api_server_port}}/healthz"
-              curl -fs 127.0.0.1:{{.kubernetes_api_server_port}}/healthz -w '\n' && break
-              sleep 2
+              echo "waiting {{.fleet_etcd_servers}}"
+              sleep 1
           done
 
-          for i in {0..60}
+          until curl -fs 127.0.0.1:{{.kubernetes_api_server_port}}/healthz
           do
-              echo "127.0.0.1:10248/healthz"
-              curl -fs 127.0.0.1:10248/healthz -w '\n' && break
-              sleep 2
+              echo "waiting 127.0.0.1:{{.kubernetes_api_server_port}}/healthz"
+              sleep 1
           done
 
-          for i in {0..60}
+          until curl -fs 127.0.0.1:10248/healthz
           do
-              echo "Machine IP registered in Fleet"
-              fleetctl --endpoint http://127.0.0.1:4001 --driver etcd list-machines \
-                --fields ip --no-legend | grep -c ${NETWORK_IP} && break
-              sleep 2
+              127.0.0.1:10248/healthz
+              sleep 1
           done
 
-          set -e
-
-          etcdctl --endpoint {{.kubernetes_etcd_servers}} cluster-health
-          etcdctl --endpoint {{.fleet_etcd_servers}} cluster-health
-
-          echo "127.0.0.1:{{.kubernetes_api_server_port}}/healthz"
-          curl -fs 127.0.0.1:{{.kubernetes_api_server_port}}/healthz -w '\n'
-
-          echo "127.0.0.1:10248/healthz"
-          curl -fs 127.0.0.1:10248/healthz -w '\n'
-
-          echo "Machine IP registered in Fleet"
-          fleetctl --endpoint http://127.0.0.1:4001 --driver etcd list-machines \
-                  --fields ip --no-legend | grep -c ${NETWORK_IP}
-
-          set +e
-
-          for i in {0..30}
+          until fleetctl --endpoint {{.fleet_etcd_servers}} --driver etcd list-machines \
+                                --fields ip --no-legend | grep -c ${NETWORK_IP}
           do
-            /opt/bin/kubectl uncordon {{.kubernetes_node_name}} && break
-            sleep 2
+              echo "waiting ${NETWORK_IP} in {{.fleet_etcd_servers}} list-machines"
+              sleep 1
+          done
+
+          until kubectl uncordon {{.kubernetes_node_name}}
+          do
+            echo "waiting kubectl uncordon {{.kubernetes_node_name}}"
+            sleep 1
           done
 
           set -e
-
-          /opt/bin/kubectl uncordon {{.kubernetes_node_name}}
 
           echo "remove the lock"
           locksmithctl -endpoint {{.kubernetes_etcd_servers}} unlock "${REQUEST_RAW_QUERY}" || true
@@ -1048,66 +1071,133 @@ storage:
         inline: |
           #!/usr/bin/env bash
 
-          set -x
-
           export VAULT_ADDR="http://127.0.0.1:8200"
-          export VAULT_CMD=/opt/bin/vault
+          export PATH=/opt/bin:${PATH}
 
-          ${VAULT_CMD} init -check && exit 0
+          vault init -check && exit 0
+
+          set -ex
 
           echo "vault init"
-          ${VAULT_CMD} init -auto -key-shares=1 -key-threshold=1 > /etc/vault.d/keys
+          vault init -key-shares=1 -key-threshold=1 > /etc/vault.d/keys
+
           UNSEALKEY1=$(cat /etc/vault.d/keys | grep "Unseal Key 1:" | cut -f4 -d ' ')
-
-          echo "vault unseal"
-          ${VAULT_CMD} unseal ${UNSEALKEY1}
-          echo "consul kv put unsealkey1"
-          /opt/bin/consul kv put unsealkey1 ${UNSEALKEY1}
-
           ROOTTOKEN=$(cat /etc/vault.d/keys | grep "Initial Root Token:" | cut -f4 -d ' ')
 
-          ${VAULT_CMD} auth ${ROOTTOKEN}
-          /opt/bin/consul kv put roottoken ${ROOTTOKEN}
+          vault unseal ${UNSEALKEY1}
+          vault auth ${ROOTTOKEN}
+          etcdctl --no-sync --endpoints http://127.0.0.1:{{.vault_etcd_client_port}} \
+            set initier "$(hostname)-${{.network.ip}}"
 
-          # wait for healthy vault
-          until ${VAULT_CMD} status
+          vault mount -path pki/etcd-kubernetes pki
+          vault mount-tune -max-lease-ttl=87600h pki/etcd-kubernetes
+          vault mounts
+
+          vault write pki/etcd-kubernetes/root/generate/internal common_name=etcd-kubernetes ttl=87600h # 10y
+          vault write pki/etcd-kubernetes/roles/member allow_any_name=true max_ttl=720h # 30j
+
+          vault policy-write etcd-kubernetes/member - << EOF
+          path "pki/etcd-kubernetes/issue/member" {
+            policy = "write"
+          }
+          EOF
+
+          vault token-create -format=json \
+            -display-name etcd-kubernetes/member \
+            -ttl="8760h" -orphan -period="8760h" \
+            -policy="etcd-kubernetes/member" | jq -er .auth.client_token | \
+              etcdctl --no-sync --endpoints http://127.0.0.1:{{.vault_etcd_client_port}} \
+                set token/etcd-kubernetes/member
+
+    - path: /opt/bin/vault-token
+      mode: 0544
+      filesystem: root
+      contents:
+        inline: |
+          #!/usr/bin/env bash
+
+          export PATH=/opt/bin:${PATH}
+          IFS=,
+          set -o pipefail
+
+          test ${1} || {
+            echo 'missing $1 eg: etcd-kubernetes'
+            exit 2
+          }
+          test ${2} || {
+            echo 'missing $2 eg: member'
+            exit 2
+          }
+
+          while true
           do
+            for ve in {{ .vault_etcd_member_client_uri_list }}
+            do
+              REQ="${ve}/v2/keys/token/${1}/${2}"
+              echo ${REQ}
+
+              TOKEN=$(curl --insecure -fL ${REQ} | jq -re .node.value)
+              if [ $? -eq 0 ]
+              then
+                echo "TOKEN=${TOKEN}" > /etc/vault.d/${1}/${2}.new
+
+                cmp /etc/vault.d/${1}/${2}.token /etc/vault.d/${1}/${2}.new
+                if [ $? -eq 0 ]
+                then
+                  echo "/etc/vault.d/${1}/${2}.token is up-to-date"
+                  exit 0
+                else
+                  mv -v /etc/vault.d/${1}/${2}.new /etc/vault.d/${1}/${2}.token
+                  exit 0
+                fi
+              fi
+            done
             sleep 1
           done
 
-    - path: /opt/bin/vault-unseal
+    - path: /opt/bin/vault-certs
       mode: 0544
       filesystem: root
       contents:
         inline: |
           #!/usr/bin/env bash
 
-          export VAULT_ADDR="http://127.0.0.1:8200"
+          export PATH=/opt/bin:${PATH}
+          IFS=,
+          set -o pipefail
 
-          until /opt/bin/vault init -check
-          do
-              sleep 10
-          done
+          test ${1} || {
+            echo 'missing $1 eg: etcd-kubernetes'
+            exit 2
+          }
+          test ${2} || {
+            echo 'missing $2 eg: member'
+            exit 2
+          }
+          test ${TOKEN} || {
+            echo 'missing ${TOKEN}'
+            exit 2
+          }
 
-          echo "Unsealing the vault..."
           while true
           do
-            /opt/bin/vault status
-            if [ $? -eq 2 ]
-            then
-              /opt/bin/consul kv get unsealkey1 | xargs /opt/bin/vault unseal
-            fi
+            for ve in {{ .vault_ip_list }}
+            do
+              export VAULT_ADDR="http://${ve}:8200"
+              vault auth ${TOKEN} || continue
+
+              vault write -format=json pki/${1}/issue/${2} common_name=$(hostname) > /etc/vault.d/${1}/${2}-certs.json
+              if [ $? -eq 0 ]
+              then
+                for item in certificate issuing_ca private_key
+                do
+                  jq -re .data.${item} /etc/vault.d/${1}/${2}-certs.json > /etc/vault.d/${1}/${2}.${item}
+                done
+                exit 0
+              fi
+            done
             sleep 5
           done
-
-    - path: /opt/bin/consul-template
-      mode: 0544
-      filesystem: root
-      contents:
-        inline: |
-          #!/usr/bin/env bash
-
-
 
 networkd:
   units:
